version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-mcp-demo
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  mysql-network:
    driver: bridge
