version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-mcp-demo
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "demo_user", "-pdemo_password"]
      timeout: 20s
      retries: 10

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp-server
    container_name: mysql-mcp-server
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
      MYSQL_DATABASE: demo_db
      LOG_LEVEL: INFO
    volumes:
      - mcp_logs:/app/logs
    networks:
      - mysql-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  mysql_data:
  mcp_logs:

networks:
  mysql-network:
    driver: bridge
